### ISSUE TITLE
Add an option to direct steam.exe manually for launching through Steam AppID

### ISSUE THREAD

**Issue by HBlaze3** [CherryMace/melvor-mod-manager#1]
I see that you have the Steam AppID functionality in processHandler.js, but for someone like me who has my steam.exe, not in a default install location, it doesn't launch Melvor through Steam.

Melvor Idle location:
![image](https://user-images.githubusercontent.com/67139870/129744843-6499e405-56b5-45c4-b15e-719dd3421ae1.png)

Steam.exe Location:
![image](https://user-images.githubusercontent.com/67139870/129745053-64e294e6-4731-48d3-8b6d-34d205635a6c.png)

Launching Melvor Idle through mod manager:
![image](https://user-images.githubusercontent.com/67139870/129745305-047c3e26-949a-445f-9868-3024806637b2.png)

I do have an example of this as well, so this is a shortcut to launch something like Old School Runescape through Steam:
E:\Steam\steam.exe "steam://rungameid/1343370"

As you can see, I had to point to my steam.exe manually then point to the AppID through the steam URI Scheme. My suggestion is to allow us to manually set our Steam install as you did with the Melvor Idle installation while still having a set default install location.

**Comment by ChaseStrackbein** [comment]
I'm curious if the latest release resolves this for you. The release that was out at the time of you submitting this issue actually didn't use the Steam command but instead launched Melvor Idle.exe directly which does not trigger the Steam integrations (achievements, overlay, etc.).

I don't see any reason why the Steam command should fail regardless of your Steam install location, but if you're still experiencing that behavior I can introduce another setting.

**Comment by HBlaze3** [comment]
It worked like a charm after the latest update with the steam URI scheme, so I guess it's just shortcuts on my pc that don't like working default with the steam URI.
