### ISSUE TITLE
Incorrect version in `package.json`

### ISSUE THREAD

**Issue by erin-allison** [CherryMace/melvor-mod-manager#10]
The latest release is listed as 0.4.2 but `package.json` still lists it as 0.4.1, which as a consequence has any builds of the app to show 0.4.1 in the user interface.

https://github.com/CherryMace/melvor-mod-manager/blob/3e453afeaebd2e2c051878c3e892f55b8d601feb/package.json#L1-L5

**Comment by ChaseStrackbein** [comment]
Whoops, I never pushed 0.4.2's changes to origin! Thanks!

fc26d9be12cf418991129be11e1b5de80fded09f
