### ISSUE TITLE
M3 doesn't close when the game is launched while steam isn't running

### ISSUE THREAD

**Issue by shenef** [CherryMace/melvor-mod-manager#8]
The close M3 upon launching toggle is turned on and launch behaviour is set to Launch using Steam.
M3 correctly launches steam and then the game but M3 stays open with an infinite loading circle on the launch button.

Version 0.4.2

**Comment by ChaseStrackbein** [comment]
What platform are you experiencing this on? PC, Mac, or Linux?

**Comment by erin-allison** [comment]
I noted this would occasionally happen on like 0.3.8 and 0.4.1, but I haven't seen it in a while since I switched to launch directly.

I'm using Linux

**Comment by shenef** [comment]
I was experiencing it on Windows 10 (i7-2600k, DDR3, SSD) and the behavior continued after upgrading to Windows 11 (i5-12600k, DDR5, SSD).

When switching to launch directly it also doesn't happen for me. My best guess would be that there is an issue with how JS is checking if steam/melvor is done launching.
Honestly i think a timeout would be enough, most machines should be able to launch it within 2 minutes or so.

**Comment by shenef** [comment]
Closed cause the project is now deprecated
