### ISSUE TITLE
Macbook M1 ARM builds

### ISSUE THREAD

**Issue by DrSkunk** [CherryMace/melvor-mod-manager#9]
For running M3 on my Mac I've succesfully cloned and built it on my M1 Mac. The resulted build works flawlessly and without adjustment.

If wanted, I can supply you with the latest build and offer to build future releases?

Thanks for this project!

**Comment by ChaseStrackbein** [comment]
That would be much appreciated, do you mind reaching out to me on Discord? Buttchouda#3950
